package com.wjy.storemanager.entity;

import java.util.Date;

public class OperationLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.user_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.username
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.module
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.action
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.ip
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_log.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.id
     *
     * @return the value of operation_log.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.id
     *
     * @param id the value for operation_log.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.user_id
     *
     * @return the value of operation_log.user_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.user_id
     *
     * @param userId the value for operation_log.user_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.username
     *
     * @return the value of operation_log.username
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.username
     *
     * @param username the value for operation_log.username
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.module
     *
     * @return the value of operation_log.module
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.module
     *
     * @param module the value for operation_log.module
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.action
     *
     * @return the value of operation_log.action
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.action
     *
     * @param action the value for operation_log.action
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.ip
     *
     * @return the value of operation_log.ip
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.ip
     *
     * @param ip the value for operation_log.ip
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_log.create_time
     *
     * @return the value of operation_log.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_log.create_time
     *
     * @param createTime the value for operation_log.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}