package com.wjy.storemanager.entity;

import java.math.BigDecimal;

public class PurchaseOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.order_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.price
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_order_detail.amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private BigDecimal amount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.id
     *
     * @return the value of purchase_order_detail.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.id
     *
     * @param id the value for purchase_order_detail.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.order_id
     *
     * @return the value of purchase_order_detail.order_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.order_id
     *
     * @param orderId the value for purchase_order_detail.order_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.product_id
     *
     * @return the value of purchase_order_detail.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.product_id
     *
     * @param productId the value for purchase_order_detail.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.quantity
     *
     * @return the value of purchase_order_detail.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.quantity
     *
     * @param quantity the value for purchase_order_detail.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.price
     *
     * @return the value of purchase_order_detail.price
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.price
     *
     * @param price the value for purchase_order_detail.price
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_order_detail.amount
     *
     * @return the value of purchase_order_detail.amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_order_detail.amount
     *
     * @param amount the value for purchase_order_detail.amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}