package com.wjy.storemanager.entity;

import org.springframework.context.annotation.Bean;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class SaleOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.customer_name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.total_amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private BigDecimal totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.status
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_order.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Date createTime;




    private List<SaleOrderDetail> saleOrderDetailList;

    public List<SaleOrderDetail> getSaleOrderDetailList() {
        return saleOrderDetailList;
    }

    public void setSaleOrderDetailList(List<SaleOrderDetail> saleOrderDetailList) {
        this.saleOrderDetailList = saleOrderDetailList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.id
     *
     * @return the value of sale_order.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.id
     *
     * @param id the value for sale_order.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.order_no
     *
     * @return the value of sale_order.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.order_no
     *
     * @param orderNo the value for sale_order.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.customer_name
     *
     * @return the value of sale_order.customer_name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.customer_name
     *
     * @param customerName the value for sale_order.customer_name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.total_amount
     *
     * @return the value of sale_order.total_amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.total_amount
     *
     * @param totalAmount the value for sale_order.total_amount
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.status
     *
     * @return the value of sale_order.status
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.status
     *
     * @param status the value for sale_order.status
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.operator_id
     *
     * @return the value of sale_order.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.operator_id
     *
     * @param operatorId the value for sale_order.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.remark
     *
     * @return the value of sale_order.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.remark
     *
     * @param remark the value for sale_order.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_order.create_time
     *
     * @return the value of sale_order.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_order.create_time
     *
     * @param createTime the value for sale_order.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}