package com.wjy.storemanager.entity;

import java.util.Date;

public class StockRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.after_stock
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Integer afterStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.biz_type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_record.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.id
     *
     * @return the value of stock_record.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.id
     *
     * @param id the value for stock_record.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.product_id
     *
     * @return the value of stock_record.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.product_id
     *
     * @param productId the value for stock_record.product_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.type
     *
     * @return the value of stock_record.type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.type
     *
     * @param type the value for stock_record.type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.quantity
     *
     * @return the value of stock_record.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.quantity
     *
     * @param quantity the value for stock_record.quantity
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.after_stock
     *
     * @return the value of stock_record.after_stock
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Integer getAfterStock() {
        return afterStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.after_stock
     *
     * @param afterStock the value for stock_record.after_stock
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setAfterStock(Integer afterStock) {
        this.afterStock = afterStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.biz_type
     *
     * @return the value of stock_record.biz_type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.biz_type
     *
     * @param bizType the value for stock_record.biz_type
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.order_no
     *
     * @return the value of stock_record.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.order_no
     *
     * @param orderNo the value for stock_record.order_no
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.operator_id
     *
     * @return the value of stock_record.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.operator_id
     *
     * @param operatorId the value for stock_record.operator_id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_record.create_time
     *
     * @return the value of stock_record.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_record.create_time
     *
     * @param createTime the value for stock_record.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}