package com.wjy.storemanager.entity;

import java.util.Date;

public class Supplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contact
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contact
     *
     * @return the value of supplier.contact
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contact
     *
     * @param contact the value for supplier.contact
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone
     *
     * @return the value of supplier.phone
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone
     *
     * @param phone the value for supplier.phone
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address
     *
     * @return the value of supplier.address
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address
     *
     * @param address the value for supplier.address
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.remark
     *
     * @return the value of supplier.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.remark
     *
     * @param remark the value for supplier.remark
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.create_time
     *
     * @return the value of supplier.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.create_time
     *
     * @param createTime the value for supplier.create_time
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}