package com.wjy.storemanager.mapper;

import com.wjy.storemanager.entity.Product;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import javax.lang.model.element.Name;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Delete({
        "delete from product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Insert({
        "insert into product (id, name, ",
        "barcode, category_id, ",
        "spec, unit, purchase_price, ",
        "sale_price, stock, ",
        "warning_threshold, status, ",
        "create_time, update_time)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{barcode,jdbcType=VARCHAR}, #{categoryId,jdbcType=BIGINT}, ",
        "#{spec,jdbcType=VARCHAR}, #{unit,jdbcType=VARCHAR}, #{purchasePrice,jdbcType=DECIMAL}, ",
        "#{salePrice,jdbcType=DECIMAL}, #{stock,jdbcType=INTEGER}, ",
        "#{warningThreshold,jdbcType=INTEGER}, #{status,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, name, barcode, category_id, spec, unit, purchase_price, sale_price, stock, ",
        "warning_threshold, status, create_time, update_time",
        "from product",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="barcode", property="barcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="purchase_price", property="purchasePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="sale_price", property="salePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="warning_threshold", property="warningThreshold", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    Product selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *多条件查询
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
            "<script>",
            "select id, name, barcode, category_id, spec, unit, purchase_price, sale_price, stock, warning_threshold, status, create_time, update_time",
            "from product",
            "<where>",
            "<if test=\"name!=null and name!=''\">and name like concat('%',#{name},'%')</if>",
            "<if test=\"categoryId!=null and categoryId!=''\">and category_id=#{categoryId}</if>",
            "<if test=\"barcode!=null and barcode!=''\">and barcode=#{barcode}</if>",
            "</where>",
            "</script>"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="barcode", property="barcode", jdbcType=JdbcType.VARCHAR),
        @Result(column="category_id", property="categoryId", jdbcType=JdbcType.BIGINT),
        @Result(column="spec", property="spec", jdbcType=JdbcType.VARCHAR),
        @Result(column="unit", property="unit", jdbcType=JdbcType.VARCHAR),
        @Result(column="purchase_price", property="purchasePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="sale_price", property="salePrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="stock", property="stock", jdbcType=JdbcType.INTEGER),
        @Result(column="warning_threshold", property="warningThreshold", jdbcType=JdbcType.INTEGER),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Product> selectAll(@Param("name") String name ,
                            @Param("categoryId")Long categoryId,
                            @Param("barcode")String barcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Update({
           "<script>",
            "update product",
            "<set>",
            "  <if test=\"name != null\">" +
                    "name = #{name},</if>",
            "  <if test=\"barcode != null\">" +
                    "barcode = #{barcode},</if>",
            "  <if test=\"categoryId != null\">" +
                    "category_id = #{categoryId},</if>",
            "  <if test=\"spec != null\">" +
                    "spec = #{spec},</if>",
            "  <if test=\"unit != null\">" +
                    "unit = #{unit},</if>",
            "  <if test=\"purchasePrice != null\">" +
                    "purchase_price = #{purchasePrice},</if>",
            "  <if test=\"salePrice != null\">" +
                    "sale_price = #{salePrice},</if>",
            "  <if test=\"stock != null\">" +
                    "stock = #{stock},</if>",
            "  <if test=\"warningThreshold != null\">" +
                    "warning_threshold = #{warningThreshold},</if>",
            "  <if test=\"status != null\">" +
                    "status = #{status},</if>",
            "  <if test=\"updateTime != null\">" +
                    "update_time = #{updateTime},</if>",
            "</set>",
            "where id = #{id}",

            "</script>"
    })
    int updateByPrimaryKey(Product row);

@Update("update product set stock=stock+#{delta} ,update_time=now() where id=#{id}")
    int updateStock(@Param("delta")Integer delta,
                    @Param("id")Long id);







}