package com.wjy.storemanager.mapper;

import com.wjy.storemanager.entity.PurchaseOrder;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface PurchaseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Delete({
        "delete from purchase_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Insert({
        "insert into purchase_order (id, order_no, ",
        "supplier_id, total_amount, ",
        "status, operator_id, ",
        "remark, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{orderNo,jdbcType=VARCHAR}, ",
        "#{supplierId,jdbcType=BIGINT}, #{totalAmount,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=TINYINT}, #{operatorId,jdbcType=BIGINT}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(PurchaseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, order_no, supplier_id, total_amount, status, operator_id, remark, create_time",
        "from purchase_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_id", property="supplierId", jdbcType=JdbcType.BIGINT),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    PurchaseOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, order_no, supplier_id, total_amount, status, operator_id, remark, create_time",
        "from purchase_order"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="supplier_id", property="supplierId", jdbcType=JdbcType.BIGINT),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<PurchaseOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Update({
        "update purchase_order",
        "set order_no = #{orderNo,jdbcType=VARCHAR},",
          "supplier_id = #{supplierId,jdbcType=BIGINT},",
          "total_amount = #{totalAmount,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=TINYINT},",
          "operator_id = #{operatorId,jdbcType=BIGINT},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PurchaseOrder row);







}