package com.wjy.storemanager.mapper;

import com.wjy.storemanager.entity.SaleOrder;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface SaleOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Delete({
        "delete from sale_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Insert({
        "insert into sale_order (id, order_no, ",
        "customer_name, total_amount, ",
        "status, operator_id, ",
        "remark, create_time)",
        "values (#{id,jdbcType=BIGINT}, #{orderNo,jdbcType=VARCHAR}, ",
        "#{customerName,jdbcType=VARCHAR}, #{totalAmount,jdbcType=DECIMAL}, ",
        "#{status,jdbcType=TINYINT}, #{operatorId,jdbcType=BIGINT}, ",
        "#{remark,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(SaleOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, order_no, customer_name, total_amount, status, operator_id, remark, create_time",
        "from sale_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="customer_name", property="customerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SaleOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, order_no, customer_name, total_amount, status, operator_id, remark, create_time",
        "from sale_order"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="customer_name", property="customerName", jdbcType=JdbcType.VARCHAR),
        @Result(column="total_amount", property="totalAmount", jdbcType=JdbcType.DECIMAL),
        @Result(column="status", property="status", jdbcType=JdbcType.TINYINT),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<SaleOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_order
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Update({
        "update sale_order",
        "set order_no = #{orderNo,jdbcType=VARCHAR},",
          "customer_name = #{customerName,jdbcType=VARCHAR},",
          "total_amount = #{totalAmount,jdbcType=DECIMAL},",
          "status = #{status,jdbcType=TINYINT},",
          "operator_id = #{operatorId,jdbcType=BIGINT},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SaleOrder row);






}