package com.wjy.storemanager.mapper;

import com.wjy.storemanager.entity.StockRecord;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.jdbc.Null;
import org.apache.ibatis.type.JdbcType;

public interface StockRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Delete({
        "delete from stock_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Insert({
        "insert into stock_record (id, product_id, ",
        "type, quantity, ",
        "after_stock, biz_type, ",
        "order_no, operator_id, ",
        "create_time)",
        "values (#{id,jdbcType=BIGINT}, #{productId,jdbcType=BIGINT}, ",
        "#{type,jdbcType=TINYINT}, #{quantity,jdbcType=INTEGER}, ",
        "#{afterStock,jdbcType=INTEGER}, #{bizType,jdbcType=VARCHAR}, ",
        "#{orderNo,jdbcType=VARCHAR}, #{operatorId,jdbcType=BIGINT}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(StockRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, product_id, type, quantity, after_stock, biz_type, order_no, operator_id, ",
        "create_time",
        "from stock_record",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="after_stock", property="afterStock", jdbcType=JdbcType.INTEGER),
        @Result(column="biz_type", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    StockRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Select({
        "select",
        "id, product_id, type, quantity, after_stock, biz_type, order_no, operator_id, ",
        "create_time",
        "from stock_record"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="product_id", property="productId", jdbcType=JdbcType.BIGINT),
        @Result(column="type", property="type", jdbcType=JdbcType.TINYINT),
        @Result(column="quantity", property="quantity", jdbcType=JdbcType.INTEGER),
        @Result(column="after_stock", property="afterStock", jdbcType=JdbcType.INTEGER),
        @Result(column="biz_type", property="bizType", jdbcType=JdbcType.VARCHAR),
        @Result(column="order_no", property="orderNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="operator_id", property="operatorId", jdbcType=JdbcType.BIGINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<StockRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_record
     *
     * @mbg.generated Mon Aug 10 14:56:46 CST 2026
     */
    @Update({
        "update stock_record",
        "set product_id = #{productId,jdbcType=BIGINT},",
          "type = #{type,jdbcType=TINYINT},",
          "quantity = #{quantity,jdbcType=INTEGER},",
          "after_stock = #{afterStock,jdbcType=INTEGER},",
          "biz_type = #{bizType,jdbcType=VARCHAR},",
          "order_no = #{orderNo,jdbcType=VARCHAR},",
          "operator_id = #{operatorId,jdbcType=BIGINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(StockRecord row);


    //动态查询流水
 @Select({"<script>",
         "select sr.*,p.name from stock_record as sr ",
         "left join product as p on sr.product_id=p.id",
         "<where>",
         "<if test=\"productId!=null\"> and sr.product_id=#{productId}</if>",
         "<if test=\"type!=null\">and sr.type=#{type}</if>",
         "</where>",
         "order by sr.id desc",
         "</script>"})
List<StockRecord> selectStockRecord(@Param("productId")Long productId,
                                    @Param("type")Byte type);

}